trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetAuthenticate@1
  displayName: 'NuGet Authenticate'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.100'

- script: dotnet restore src/CheckDigit.FluentValidation.sln
  displayName: 'Restore NuGet Packages'

- script: dotnet test src/CheckDigit.FluentValidation.sln
  displayName: 'Run tests'

- script: dotnet build src/CheckDigit.FluentValidation.sln --configuration $(buildConfiguration) --no-restore
  displayName: 'Build Solution'

- script: dotnet pack src/CheckDigit.FluentValidation/CheckDigit.FluentValidation.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Pack Project'

- script: dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg --api-key $(System.AccessToken) --source https://pkgs.dev.azure.com/marcoshidalgonunes/CheckDigit/_packaging/CheckDigit/nuget/v3/index.json
  displayName: 'Push NuGet Package'